#!/bin/sh

set -eux

cd "$AUTOPKGTEST_TMP"

DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

"${DEB_HOST_GNU_TYPE}-gi-inspect-typelib" --print-typelibs \
    --typelib-version=2.0 GObject

"${DEB_HOST_GNU_TYPE}-gi-compile-repository" \
    -o GLib.typelib \
    "/usr/lib/${DEB_HOST_MULTIARCH}/gir-1.0/GLib-2.0.gir"

"${DEB_HOST_GNU_TYPE}-gi-decompile-typelib" \
    -o GLib.gir \
    GLib.typelib

# vim:set sts=4 sw=4 et:
